### ISSUE TITLE
cim not working

### ISSUE THREAD

**Issue by deepakmali-dgsl** [thinktandem/migration_boilerplate#3]
![image](https://user-images.githubusercontent.com/68944868/92010264-3aac3480-ed67-11ea-8585-28ed338694ee.png)

Hello Team, 
I followed all steps but during "lando drush cim -y" I am facing below issue. 
This import is empty and if applied would delete all of your configuration, so has been rejected.

I also copied files in config/sync folder and added $settings['config_sync_directory'] = 'config/sync'; but still facing issue.

Could you please help here.

**Comment by labboy0276** [comment]
My guess based on that image is your config directory is not setup correctly.  It looks like you are wiping out all your config based on the limited items I can see.

Make sure config_sync_directory is pointed to the right directory.

**Comment by deepakmali-dgsl** [comment]
thanks for quick response. 
I have checked look like UUID issue. I have found one step in your deck which I missed. 
![image](https://user-images.githubusercontent.com/68944868/92071841-6e21aa00-edcd-11ea-98c3-fb560fb98262.png)
